### PR TITLE
Make Docker a requirement

### PR DESCRIPTION
**Pull request by yuya-takeyama**
@quipper/sre

## Objectives

* Docker is one of the key components of SRE in Quipper
  * SREs in Quipper need to be able to use Docker
* To standardize the way to run submissions
  * Sometimes it takes a long time to make them run properly

### CODE REVIEW

**Comment by rbmrclo** [comment]
Though it's rare for me to be able to review applicants for SRE in Japan, technical-wise, I fully agree with this requirement 👍

**Comment by chaspy** [comment]
LGTM 👍

**Comment by yuya-takeyama** [comment]
@motobrew
Please check!

**Comment by motobrew** [comment]
I agree as well!

**Comment by rbmrclo** [comment]
:rocket:

**Pull request merged**
